channels:
  - conda-forge
  - defaults
dependencies:
  #- git
  - r-base>=4.0.0
  - r-tidyverse
  - r-rprojroot
  - r-desc
  - r-remotes
  - r-renv
  - ruby>=2.7.1
  - c-compiler
  - cxx-compiler
  #- rb-bundler # This and *many* other ruby gems are out of date, use gem install rb-bundler
  #- rb-github-pages # This and *many* other ruby gems are out of date, use bundle install
#Run:
# $ conda activate name-of-your-env
# $ gem install bundler
# $ bundle install
